apiVersion: apps/v1
kind: Deployment
metadata:
  name: revenueforecast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revenueforecast
  template:
    metadata:
      labels:
        app: revenueforecast
    spec:
      containers:
      - name: revenueforecast-container
        image: revenueforecast:latest  # Ensure it matches the Minikube image
        imagePullPolicy: IfNotPresent  # Prevent pulling from an external registry
        ports:
        - containerPort: 8501  # Streamlit runs on port 8501
