apiVersion: v1
kind: Service
metadata:
  name: revenueforecast
spec:
  type: NodePort
  selector:
    app: revenueforecast
  ports:
    - protocol: TCP
      port: 80          # External port
      targetPort: 8501  # Streamlit runs on 8501
      nodePort: 30001
